# Nombre de la aplicación
spring.application.name=ArteDulceMasasApp

# --- CONFIGURACIÓN DE RED (DINÁMICA) ---
server.port=${PORT:8080}

# --- CONFIGURACIÓN DE POSTGRESQL (NEON) ---
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# --- CONFIGURACIÓN DE RECURSOS ESTÁTICOS ---
spring.web.resources.static-locations=classpath:/static/
server.max-http-header-size=64KB